export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FALURE: 'FETCH_DATA_FALURE',

  TOGGLE: 'TOGGLE',
  TOGGLE_HARMBUGGER: 'TOGGLE_HARMBUGGER',

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
};
