export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  TOGGLE: 'TOGGLE',
  TOGGLE_HARMBUGGER: 'TOGGLE_HARMBUGGER',

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
};
