export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FALURE: 'FETCH_DATA_FALURE',

  TOGGLE: 'TOGGLE',
  TOGGLE_HARMBUGGER: 'TOGGLE_HARMBUGGER',

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',

  FETCH_SINGLE_COMMUNITY_REQUEST: 'FETCH_SINGLE_COMMUNITY_REQUEST',
  FETCH_SINGLE_COMMUNITY_SUCCESS: 'FETCH_SINGLE_COMMUNITY_SUCCESS',
  FETCH_SINGLE_COMMUNITY_FALURE: 'FETCH_SINGLE_COMMUNITY_FALURE',

  FETCH_COMMENT_REQUEST: 'FETCH_COMMENT_REQUEST',
  FETCH_COMMENT_SUCCESS: 'FETCH_COMMENT_SUCCESS',
  FETCH_COMMENT_FALURE: 'FETCH_COMMENT_FALURE',

  LIKE_COMMENT: 'LIKE_COMMENT',
  DISLIKECOMMENT: 'DISLIKECOMMENT',

  CREATE_COMMENT: 'CREATE_COMMENT',

  FETCH_REPLIED_COMMENT: 'FETCH_REPLIED_COMMENT',
  CREATE_REPLIED_COMMENT: 'CREATE_REPLIED_COMMENT',

  JOIN_COMMUNITY: 'JOIN_COMMUNITY',
};
